name: publish

on:
    release:
        types: [created]

jobs:
    test:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/

            - run: node test

    publish:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/

            - env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
              run: npm publish
