name: test

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    test:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - run: node --test-reporter spec --test
